### ISSUE TITLE
组件可视化

### ISSUE THREAD

**Issue by 76wenshu** [colaboy/seedsui-react#28]
建议提供一个可视化的展示或者提供组件使用的图片，增强新人对组件的认知。

**Comment by colaboy** [comment]
写文档需要大量的时间，没有时间



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年2月28日(星期一) 下午5:09
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [colaboy/seedsui-react] 组件可视化 (Issue #28)





 
建议提供一个可视化的展示或者提供组件使用的图片，增强新人对组件的认知。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 76wenshu** [comment]
有时间我也来看看这个搞一个可视化
